-- ═════════════════════════════════════════════════════════════════════════════
-- Migration 025: Security Hardening
-- Sources: Supabase security/performance advisors + internal audit (2026-06-09)
--
-- Sections:
--   1. SECURITY DEFINER functions — pin search_path, fix avatar_url & plan validation
--   2. REVOKE EXECUTE from anon on callable SECURITY DEFINER functions
--   3. Covering indexes for workspace_members / organization_members RLS subqueries
--   4. Missing FK indexes (performance advisor: unindexed_foreign_keys)
--   5. GIN indexes on JSONB targeting/rules columns
--   6. Composite index for pixel_events time-range queries
--   7. Rebuild ALL RLS policies with (SELECT auth.uid()) caching
--      — eliminates per-row re-evaluation (auth_rls_initplan WARN)
--   8. Fix policy scope issues (creative_assets FOR ALL, ai_diagnostics FOR ALL,
--      campaign_benchmarks FOR ALL, pixels DELETE role gap)
--   9. Admin self-escalation prevention trigger
--  10. Explicit deny policies on append-only tables (billing_events, creative_versions)
--  11. Add updated_at to creative_assets
-- ═════════════════════════════════════════════════════════════════════════════

-- ─────────────────────────────────────────────────────────────────────────────
-- 1. SECURITY DEFINER FUNCTIONS — pin search_path + security fixes
--    Supabase advisory: function_search_path_mutable (WARN)
-- ─────────────────────────────────────────────────────────────────────────────

CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS TRIGGER LANGUAGE plpgsql
SET search_path = public, pg_temp AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$;

-- handle_new_user: added avatar_url scheme validation (XSS/SSRF guard)
CREATE OR REPLACE FUNCTION handle_new_user()
RETURNS TRIGGER LANGUAGE plpgsql SECURITY DEFINER
SET search_path = public, pg_temp AS $$
DECLARE
  v_display_name TEXT;
  v_avatar_url   TEXT;
BEGIN
  v_display_name := COALESCE(
    NULLIF(TRIM(NEW.raw_user_meta_data->>'display_name'), ''),
    NULLIF(TRIM(NEW.raw_user_meta_data->>'full_name'), ''),
    SPLIT_PART(NEW.email, '@', 1)
  );
  -- Only accept http/https avatar URLs; discard javascript: and data: URIs
  v_avatar_url := NEW.raw_user_meta_data->>'avatar_url';
  IF v_avatar_url IS NOT NULL AND v_avatar_url !~ '^https?://' THEN
    v_avatar_url := NULL;
  END IF;
  INSERT INTO public.profiles (id, display_name, avatar_url)
  VALUES (NEW.id, v_display_name, v_avatar_url)
  ON CONFLICT (id) DO NOTHING;
  RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION current_user_org_role(org_id UUID)
RETURNS org_role LANGUAGE sql SECURITY DEFINER STABLE
SET search_path = public, pg_temp AS $$
  SELECT role FROM organization_members
  WHERE organization_id = org_id
    AND user_id = auth.uid()
  LIMIT 1;
$$;

CREATE OR REPLACE FUNCTION current_user_ws_role(ws_id UUID)
RETURNS org_role LANGUAGE sql SECURITY DEFINER STABLE
SET search_path = public, pg_temp AS $$
  SELECT role FROM workspace_members
  WHERE workspace_id = ws_id
    AND user_id = auth.uid()
  LIMIT 1;
$$;

CREATE OR REPLACE FUNCTION is_superadmin()
RETURNS BOOLEAN LANGUAGE sql SECURITY DEFINER STABLE
SET search_path = public, pg_temp AS $$
  SELECT EXISTS (
    SELECT 1 FROM organization_members
    WHERE user_id = auth.uid() AND role = 'superadmin'
  );
$$;

-- sync_org_plan: added plan value validation to prevent plan spoofing
CREATE OR REPLACE FUNCTION sync_org_plan()
RETURNS TRIGGER LANGUAGE plpgsql SECURITY DEFINER
SET search_path = public, pg_temp AS $$
BEGIN
  IF NEW.plan NOT IN ('free', 'pro', 'agency') THEN
    RAISE EXCEPTION 'sync_org_plan: invalid plan value: %', NEW.plan;
  END IF;
  UPDATE organizations
  SET plan = NEW.plan, updated_at = NOW()
  WHERE id = NEW.organization_id;
  RETURN NEW;
END;
$$;

-- update_ai_diagnostics_updated_at may be auto-generated by Supabase; fix search_path safely
DO $$
BEGIN
  ALTER FUNCTION update_ai_diagnostics_updated_at() SET search_path = public, pg_temp;
EXCEPTION WHEN undefined_function THEN NULL;
END $$;

-- ─────────────────────────────────────────────────────────────────────────────
-- 2. REVOKE EXECUTE FROM anon ON CALLABLE SECURITY DEFINER FUNCTIONS
--    Supabase advisory: anon_security_definer_function_executable (WARN)
-- ─────────────────────────────────────────────────────────────────────────────

-- RLS helpers: revoke anon-callable RPC; authenticated role retains access for RLS
REVOKE EXECUTE ON FUNCTION current_user_org_role(uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION current_user_ws_role(uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION is_superadmin() FROM anon;

-- Trigger-only functions: no user role should call these directly
REVOKE EXECUTE ON FUNCTION handle_new_user() FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION sync_org_plan()   FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION set_updated_at()  FROM anon, authenticated;

-- rls_auto_enable is an internal maintenance function
DO $$
BEGIN
  REVOKE EXECUTE ON FUNCTION rls_auto_enable() FROM anon, authenticated;
EXCEPTION WHEN undefined_function THEN NULL;
END $$;

-- ─────────────────────────────────────────────────────────────────────────────
-- 3. COVERING INDEXES FOR workspace_members AND organization_members
--    RLS subqueries join on (user_id, role, workspace_id/organization_id).
--    Replacing simple user_id indexes with covering composites eliminates heap
--    fetches during role-filtered policy evaluation.
-- ─────────────────────────────────────────────────────────────────────────────

DROP INDEX IF EXISTS ws_members_user_id_idx;
CREATE INDEX IF NOT EXISTS ws_members_user_id_role_ws_idx
  ON workspace_members (user_id, role, workspace_id);

DROP INDEX IF EXISTS org_members_user_id_idx;
CREATE INDEX IF NOT EXISTS org_members_user_id_role_org_idx
  ON organization_members (user_id, role, organization_id);

-- ─────────────────────────────────────────────────────────────────────────────
-- 4. MISSING FK INDEXES
--    Performance advisor: unindexed_foreign_keys (INFO)
-- ─────────────────────────────────────────────────────────────────────────────

-- alert_notifications
CREATE INDEX IF NOT EXISTS alert_notifications_workspace_id_idx
  ON alert_notifications (workspace_id);
CREATE INDEX IF NOT EXISTS alert_notifications_rule_id_idx
  ON alert_notifications (rule_id);
CREATE INDEX IF NOT EXISTS alert_notifications_campaign_id_idx
  ON alert_notifications (campaign_id) WHERE campaign_id IS NOT NULL;

-- alert_rules
CREATE INDEX IF NOT EXISTS alert_rules_workspace_id_idx
  ON alert_rules (workspace_id);
CREATE INDEX IF NOT EXISTS alert_rules_campaign_id_idx
  ON alert_rules (campaign_id) WHERE campaign_id IS NOT NULL;

-- campaign_benchmarks
CREATE INDEX IF NOT EXISTS campaign_benchmarks_workspace_id_idx
  ON campaign_benchmarks (workspace_id) WHERE workspace_id IS NOT NULL;

-- creative_versions
CREATE INDEX IF NOT EXISTS creative_versions_workspace_id_idx
  ON creative_versions (workspace_id);

-- creatives self-referential FK
CREATE INDEX IF NOT EXISTS creatives_parent_id_idx
  ON creatives (parent_id) WHERE parent_id IS NOT NULL;

-- pixels
CREATE INDEX IF NOT EXISTS pixels_workspace_id_idx
  ON pixels (workspace_id);

-- rtb_campaigns
CREATE INDEX IF NOT EXISTS rtb_campaigns_campaign_id_idx
  ON rtb_campaigns (campaign_id) WHERE campaign_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS rtb_campaigns_creative_id_idx
  ON rtb_campaigns (creative_id) WHERE creative_id IS NOT NULL;

-- org_api_credentials (used in RLS subquery on organization_id)
CREATE INDEX IF NOT EXISTS org_api_credentials_org_id_idx
  ON org_api_credentials (organization_id);

-- ─────────────────────────────────────────────────────────────────────────────
-- 5. GIN INDEXES ON JSONB TARGETING / RULES COLUMNS
--    RTB bid evaluation and DMP audience matching query these with @> / ? operators.
-- ─────────────────────────────────────────────────────────────────────────────

CREATE INDEX IF NOT EXISTS ad_sets_targeting_gin_idx
  ON ad_sets USING GIN (targeting);

CREATE INDEX IF NOT EXISTS rtb_campaigns_targeting_gin_idx
  ON rtb_campaigns USING GIN (targeting);

CREATE INDEX IF NOT EXISTS audiences_rules_gin_idx
  ON audiences USING GIN (rules);

-- ─────────────────────────────────────────────────────────────────────────────
-- 6. COMPOSITE INDEX FOR pixel_events TIME-RANGE QUERIES
--    Analytics views GROUP BY pixel_id ORDER BY received_at — single-column
--    indexes force an extra heap fetch; composite index makes it index-only.
-- ─────────────────────────────────────────────────────────────────────────────

CREATE INDEX IF NOT EXISTS pixel_events_pixel_received_idx
  ON pixel_events (pixel_id, received_at DESC);

-- ─────────────────────────────────────────────────────────────────────────────
-- 7. REBUILD ALL RLS POLICIES WITH (SELECT auth.uid()) CACHING
--    Supabase advisory: auth_rls_initplan (WARN) — bare auth.uid() re-evaluates
--    per row. Wrapping in (SELECT auth.uid()) causes the planner to cache the
--    result for the entire query.
-- ─────────────────────────────────────────────────────────────────────────────

-- ── organizations ────────────────────────────────────────────────────────────

DROP POLICY IF EXISTS "org_select" ON organizations;
CREATE POLICY "org_select" ON organizations FOR SELECT
  USING (
    is_superadmin()
    OR EXISTS (
      SELECT 1 FROM organization_members
      WHERE organization_id = id AND user_id = (SELECT auth.uid())
    )
  );

DROP POLICY IF EXISTS "org_insert" ON organizations;
CREATE POLICY "org_insert" ON organizations FOR INSERT
  WITH CHECK ((SELECT auth.uid()) IS NOT NULL);

-- ── workspaces ────────────────────────────────────────────────────────────────

DROP POLICY IF EXISTS "ws_select" ON workspaces;
CREATE POLICY "ws_select" ON workspaces FOR SELECT
  USING (
    is_superadmin()
    OR EXISTS (
      SELECT 1 FROM workspace_members
      WHERE workspace_id = id AND user_id = (SELECT auth.uid())
    )
  );

-- ── profiles ─────────────────────────────────────────────────────────────────

DROP POLICY IF EXISTS "profile_select" ON profiles;
CREATE POLICY "profile_select" ON profiles FOR SELECT
  USING (id = (SELECT auth.uid()) OR is_superadmin());

DROP POLICY IF EXISTS "profile_update" ON profiles;
CREATE POLICY "profile_update" ON profiles FOR UPDATE
  USING    (id = (SELECT auth.uid()))
  WITH CHECK (id = (SELECT auth.uid()));

-- ── organization_members ─────────────────────────────────────────────────────

DROP POLICY IF EXISTS "org_members_select" ON organization_members;
CREATE POLICY "org_members_select" ON organization_members FOR SELECT
  USING (
    is_superadmin()
    OR user_id = (SELECT auth.uid())
    OR current_user_org_role(organization_id) IN ('owner', 'admin')
  );

DROP POLICY IF EXISTS "org_members_insert" ON organization_members;
CREATE POLICY "org_members_insert" ON organization_members FOR INSERT
  WITH CHECK (
    role != 'superadmin'
    AND (
      current_user_org_role(organization_id) IN ('owner', 'admin', 'superadmin')
      OR (
        user_id = (SELECT auth.uid())
        AND role = 'owner'
        AND NOT EXISTS (
          SELECT 1 FROM organization_members om
          WHERE om.organization_id = organization_members.organization_id
        )
      )
    )
  );

-- ── workspace_members ─────────────────────────────────────────────────────────

DROP POLICY IF EXISTS "ws_members_select" ON workspace_members;
CREATE POLICY "ws_members_select" ON workspace_members FOR SELECT
  USING (
    is_superadmin()
    OR user_id = (SELECT auth.uid())
    OR current_user_ws_role(workspace_id) IN ('owner', 'admin')
  );

-- ── campaigns ─────────────────────────────────────────────────────────────────

DROP POLICY IF EXISTS campaigns_select ON campaigns;
CREATE POLICY campaigns_select ON campaigns FOR SELECT
  USING (EXISTS (
    SELECT 1 FROM workspace_members wm
    WHERE wm.workspace_id = campaigns.workspace_id
      AND wm.user_id = (SELECT auth.uid())
  ));

DROP POLICY IF EXISTS campaigns_insert ON campaigns;
CREATE POLICY campaigns_insert ON campaigns FOR INSERT
  WITH CHECK (EXISTS (
    SELECT 1 FROM workspace_members wm
    WHERE wm.workspace_id = campaigns.workspace_id
      AND wm.user_id = (SELECT auth.uid())
      AND wm.role IN ('owner', 'admin', 'member')
  ));

DROP POLICY IF EXISTS campaigns_update ON campaigns;
CREATE POLICY campaigns_update ON campaigns FOR UPDATE
  USING (EXISTS (
    SELECT 1 FROM workspace_members wm
    WHERE wm.workspace_id = campaigns.workspace_id
      AND wm.user_id = (SELECT auth.uid())
      AND wm.role IN ('owner', 'admin', 'member')
  ));

DROP POLICY IF EXISTS campaigns_delete ON campaigns;
CREATE POLICY campaigns_delete ON campaigns FOR DELETE
  USING (EXISTS (
    SELECT 1 FROM workspace_members wm
    WHERE wm.workspace_id = campaigns.workspace_id
      AND wm.user_id = (SELECT auth.uid())
      AND wm.role IN ('owner', 'admin')
  ));

-- ── ad_sets ───────────────────────────────────────────────────────────────────

DROP POLICY IF EXISTS ad_sets_select ON ad_sets;
CREATE POLICY ad_sets_select ON ad_sets FOR SELECT
  USING (EXISTS (
    SELECT 1 FROM workspace_members wm
    WHERE wm.workspace_id = ad_sets.workspace_id
      AND wm.user_id = (SELECT auth.uid())
  ));

DROP POLICY IF EXISTS ad_sets_insert ON ad_sets;
CREATE POLICY ad_sets_insert ON ad_sets FOR INSERT
  WITH CHECK (EXISTS (
    SELECT 1 FROM workspace_members wm
    WHERE wm.workspace_id = ad_sets.workspace_id
      AND wm.user_id = (SELECT auth.uid())
      AND wm.role IN ('owner', 'admin', 'member')
  ));

DROP POLICY IF EXISTS ad_sets_update ON ad_sets;
CREATE POLICY ad_sets_update ON ad_sets FOR UPDATE
  USING (EXISTS (
    SELECT 1 FROM workspace_members wm
    WHERE wm.workspace_id = ad_sets.workspace_id
      AND wm.user_id = (SELECT auth.uid())
      AND wm.role IN ('owner', 'admin', 'member')
  ));

DROP POLICY IF EXISTS ad_sets_delete ON ad_sets;
CREATE POLICY ad_sets_delete ON ad_sets FOR DELETE
  USING (EXISTS (
    SELECT 1 FROM workspace_members wm
    WHERE wm.workspace_id = ad_sets.workspace_id
      AND wm.user_id = (SELECT auth.uid())
      AND wm.role IN ('owner', 'admin')
  ));

-- ── ads ───────────────────────────────────────────────────────────────────────

DROP POLICY IF EXISTS ads_select ON ads;
CREATE POLICY ads_select ON ads FOR SELECT
  USING (EXISTS (
    SELECT 1 FROM workspace_members wm
    WHERE wm.workspace_id = ads.workspace_id
      AND wm.user_id = (SELECT auth.uid())
  ));

DROP POLICY IF EXISTS ads_insert ON ads;
CREATE POLICY ads_insert ON ads FOR INSERT
  WITH CHECK (EXISTS (
    SELECT 1 FROM workspace_members wm
    WHERE wm.workspace_id = ads.workspace_id
      AND wm.user_id = (SELECT auth.uid())
      AND wm.role IN ('owner', 'admin', 'member')
  ));

DROP POLICY IF EXISTS ads_update ON ads;
CREATE POLICY ads_update ON ads FOR UPDATE
  USING (EXISTS (
    SELECT 1 FROM workspace_members wm
    WHERE wm.workspace_id = ads.workspace_id
      AND wm.user_id = (SELECT auth.uid())
      AND wm.role IN ('owner', 'admin', 'member')
  ));

DROP POLICY IF EXISTS ads_delete ON ads;
CREATE POLICY ads_delete ON ads FOR DELETE
  USING (EXISTS (
    SELECT 1 FROM workspace_members wm
    WHERE wm.workspace_id = ads.workspace_id
      AND wm.user_id = (SELECT auth.uid())
      AND wm.role IN ('owner', 'admin')
  ));

-- ── pixels ────────────────────────────────────────────────────────────────────

DROP POLICY IF EXISTS "pixels: workspace members can read" ON pixels;
CREATE POLICY "pixels: workspace members can read"
  ON pixels FOR SELECT
  USING (workspace_id IN (
    SELECT workspace_id FROM workspace_members WHERE user_id = (SELECT auth.uid())
  ));

DROP POLICY IF EXISTS "pixels: workspace members can insert" ON pixels;
CREATE POLICY "pixels: workspace members can insert"
  ON pixels FOR INSERT
  WITH CHECK (workspace_id IN (
    SELECT workspace_id FROM workspace_members WHERE user_id = (SELECT auth.uid())
  ));

DROP POLICY IF EXISTS "pixels: workspace members can update" ON pixels;
CREATE POLICY "pixels: workspace members can update"
  ON pixels FOR UPDATE
  USING (workspace_id IN (
    SELECT workspace_id FROM workspace_members WHERE user_id = (SELECT auth.uid())
  ));

-- Pixel deletion restricted to owners/admins — destroying a pixel removes attribution history
DROP POLICY IF EXISTS "pixels: workspace members can delete" ON pixels;
DROP POLICY IF EXISTS "pixels: owners and admins can delete" ON pixels;
CREATE POLICY "pixels: owners and admins can delete"
  ON pixels FOR DELETE
  USING (workspace_id IN (
    SELECT workspace_id FROM workspace_members
    WHERE user_id = (SELECT auth.uid()) AND role IN ('owner', 'admin')
  ));

-- ── pixel_events ─────────────────────────────────────────────────────────────

DROP POLICY IF EXISTS "pixel_events: workspace members can read" ON pixel_events;
CREATE POLICY "pixel_events: workspace members can read"
  ON pixel_events FOR SELECT
  USING (pixel_id IN (
    SELECT p.id FROM pixels p
    JOIN workspace_members wm ON wm.workspace_id = p.workspace_id
    WHERE wm.user_id = (SELECT auth.uid())
  ));

-- ── alert_rules ───────────────────────────────────────────────────────────────

DROP POLICY IF EXISTS "alert_rules: workspace members can read" ON alert_rules;
CREATE POLICY "alert_rules: workspace members can read"
  ON alert_rules FOR SELECT
  USING (workspace_id IN (
    SELECT workspace_id FROM workspace_members WHERE user_id = (SELECT auth.uid())
  ));

DROP POLICY IF EXISTS "alert_rules: workspace members can insert" ON alert_rules;
CREATE POLICY "alert_rules: workspace members can insert"
  ON alert_rules FOR INSERT
  WITH CHECK (workspace_id IN (
    SELECT workspace_id FROM workspace_members WHERE user_id = (SELECT auth.uid())
  ));

DROP POLICY IF EXISTS "alert_rules: workspace members can update" ON alert_rules;
CREATE POLICY "alert_rules: workspace members can update"
  ON alert_rules FOR UPDATE
  USING (workspace_id IN (
    SELECT workspace_id FROM workspace_members WHERE user_id = (SELECT auth.uid())
  ));

DROP POLICY IF EXISTS "alert_rules: workspace members can delete" ON alert_rules;
CREATE POLICY "alert_rules: workspace members can delete"
  ON alert_rules FOR DELETE
  USING (workspace_id IN (
    SELECT workspace_id FROM workspace_members WHERE user_id = (SELECT auth.uid())
  ));

-- ── alert_notifications ───────────────────────────────────────────────────────

DROP POLICY IF EXISTS "alert_notifications: workspace members can read" ON alert_notifications;
CREATE POLICY "alert_notifications: workspace members can read"
  ON alert_notifications FOR SELECT
  USING (workspace_id IN (
    SELECT workspace_id FROM workspace_members WHERE user_id = (SELECT auth.uid())
  ));

DROP POLICY IF EXISTS "alert_notifications: workspace members can update" ON alert_notifications;
CREATE POLICY "alert_notifications: workspace members can update"
  ON alert_notifications FOR UPDATE
  USING (workspace_id IN (
    SELECT workspace_id FROM workspace_members WHERE user_id = (SELECT auth.uid())
  ));

-- ── rtb_campaigns ─────────────────────────────────────────────────────────────

DROP POLICY IF EXISTS "rtb_campaigns_select" ON rtb_campaigns;
CREATE POLICY "rtb_campaigns_select" ON rtb_campaigns FOR SELECT
  USING (workspace_id IN (
    SELECT workspace_id FROM workspace_members WHERE user_id = (SELECT auth.uid())
  ));

DROP POLICY IF EXISTS "rtb_campaigns_insert" ON rtb_campaigns;
CREATE POLICY "rtb_campaigns_insert" ON rtb_campaigns FOR INSERT
  WITH CHECK (workspace_id IN (
    SELECT workspace_id FROM workspace_members
    WHERE user_id = (SELECT auth.uid()) AND role IN ('owner', 'admin', 'member')
  ));

DROP POLICY IF EXISTS "rtb_campaigns_update" ON rtb_campaigns;
CREATE POLICY "rtb_campaigns_update" ON rtb_campaigns FOR UPDATE
  USING (workspace_id IN (
    SELECT workspace_id FROM workspace_members
    WHERE user_id = (SELECT auth.uid()) AND role IN ('owner', 'admin', 'member')
  ));

DROP POLICY IF EXISTS "rtb_campaigns_delete" ON rtb_campaigns;
CREATE POLICY "rtb_campaigns_delete" ON rtb_campaigns FOR DELETE
  USING (workspace_id IN (
    SELECT workspace_id FROM workspace_members
    WHERE user_id = (SELECT auth.uid()) AND role IN ('owner', 'admin')
  ));

-- ── bid_requests_log ─────────────────────────────────────────────────────────

DROP POLICY IF EXISTS "workspace members can read bid logs" ON bid_requests_log;
CREATE POLICY "workspace members can read bid logs"
  ON bid_requests_log FOR SELECT
  USING (workspace_id IN (
    SELECT workspace_id FROM workspace_members WHERE user_id = (SELECT auth.uid())
  ));

-- ── audiences ─────────────────────────────────────────────────────────────────

DROP POLICY IF EXISTS "audiences_select" ON audiences;
CREATE POLICY "audiences_select" ON audiences FOR SELECT
  USING (workspace_id IN (
    SELECT workspace_id FROM workspace_members WHERE user_id = (SELECT auth.uid())
  ));

DROP POLICY IF EXISTS "audiences_insert" ON audiences;
CREATE POLICY "audiences_insert" ON audiences FOR INSERT
  WITH CHECK (workspace_id IN (
    SELECT workspace_id FROM workspace_members WHERE user_id = (SELECT auth.uid())
  ));

DROP POLICY IF EXISTS "audiences_update" ON audiences;
CREATE POLICY "audiences_update" ON audiences FOR UPDATE
  USING (workspace_id IN (
    SELECT workspace_id FROM workspace_members WHERE user_id = (SELECT auth.uid())
  ));

DROP POLICY IF EXISTS "audiences_delete" ON audiences;
CREATE POLICY "audiences_delete" ON audiences FOR DELETE
  USING (workspace_id IN (
    SELECT workspace_id FROM workspace_members WHERE user_id = (SELECT auth.uid())
  ));

-- ── audience_segments ─────────────────────────────────────────────────────────

DROP POLICY IF EXISTS "workspace members can read segments" ON audience_segments;
CREATE POLICY "workspace members can read segments"
  ON audience_segments FOR SELECT
  USING (audience_id IN (
    SELECT id FROM audiences WHERE workspace_id IN (
      SELECT workspace_id FROM workspace_members WHERE user_id = (SELECT auth.uid())
    )
  ));

-- ── org_api_credentials ───────────────────────────────────────────────────────

DROP POLICY IF EXISTS "api_creds: owners and admins can read" ON org_api_credentials;
CREATE POLICY "api_creds: owners and admins can read"
  ON org_api_credentials FOR SELECT
  USING (organization_id IN (
    SELECT organization_id FROM organization_members
    WHERE user_id = (SELECT auth.uid()) AND role IN ('owner', 'admin')
  ));

DROP POLICY IF EXISTS "api_creds: owners and admins can write" ON org_api_credentials;
CREATE POLICY "api_creds: owners and admins can write"
  ON org_api_credentials FOR INSERT
  WITH CHECK (organization_id IN (
    SELECT organization_id FROM organization_members
    WHERE user_id = (SELECT auth.uid()) AND role IN ('owner', 'admin')
  ));

DROP POLICY IF EXISTS "api_creds: owners and admins can update" ON org_api_credentials;
CREATE POLICY "api_creds: owners and admins can update"
  ON org_api_credentials FOR UPDATE
  USING (organization_id IN (
    SELECT organization_id FROM organization_members
    WHERE user_id = (SELECT auth.uid()) AND role IN ('owner', 'admin')
  ))
  WITH CHECK (organization_id IN (
    SELECT organization_id FROM organization_members
    WHERE user_id = (SELECT auth.uid()) AND role IN ('owner', 'admin')
  ));

DROP POLICY IF EXISTS "api_creds: owners and admins can delete" ON org_api_credentials;
CREATE POLICY "api_creds: owners and admins can delete"
  ON org_api_credentials FOR DELETE
  USING (organization_id IN (
    SELECT organization_id FROM organization_members
    WHERE user_id = (SELECT auth.uid()) AND role IN ('owner', 'admin')
  ));

-- ── sync_runs ─────────────────────────────────────────────────────────────────
-- Removed the auth.role()='service_role' INSERT/UPDATE policies — service role
-- bypasses RLS natively; those policies had zero runtime effect.

DROP POLICY IF EXISTS "sync_runs: workspace members can read" ON sync_runs;
CREATE POLICY "sync_runs: workspace members can read"
  ON sync_runs FOR SELECT
  USING (workspace_id IN (
    SELECT workspace_id FROM workspace_members WHERE user_id = (SELECT auth.uid())
  ));

DROP POLICY IF EXISTS "sync_runs: service role can insert" ON sync_runs;
DROP POLICY IF EXISTS "sync_runs: service role can update" ON sync_runs;

DROP POLICY IF EXISTS "sync_runs: owners and admins can delete" ON sync_runs;
CREATE POLICY "sync_runs: owners and admins can delete"
  ON sync_runs FOR DELETE
  USING (workspace_id IN (
    SELECT w.id FROM workspaces w
    JOIN organization_members om
      ON om.organization_id = w.organization_id
     AND om.user_id = (SELECT auth.uid())
     AND om.role IN ('owner', 'admin')
  ));

-- ── campaign_metrics_daily ────────────────────────────────────────────────────
-- Same pattern: removed auth.role()='service_role' policies (no effect).

DROP POLICY IF EXISTS "cmd: workspace members can read" ON campaign_metrics_daily;
CREATE POLICY "cmd: workspace members can read"
  ON campaign_metrics_daily FOR SELECT
  USING (workspace_id IN (
    SELECT workspace_id FROM workspace_members WHERE user_id = (SELECT auth.uid())
  ));

DROP POLICY IF EXISTS "cmd: service role can insert" ON campaign_metrics_daily;
DROP POLICY IF EXISTS "cmd: service role can update" ON campaign_metrics_daily;

DROP POLICY IF EXISTS "cmd: owners and admins can delete" ON campaign_metrics_daily;
CREATE POLICY "cmd: owners and admins can delete"
  ON campaign_metrics_daily FOR DELETE
  USING (workspace_id IN (
    SELECT w.id FROM workspaces w
    JOIN organization_members om
      ON om.organization_id = w.organization_id
     AND om.user_id = (SELECT auth.uid())
     AND om.role IN ('owner', 'admin')
  ));

-- ─────────────────────────────────────────────────────────────────────────────
-- 8. POLICY SCOPE FIXES
-- ─────────────────────────────────────────────────────────────────────────────

-- ── billing_events: fix SELECT + add fixed auth.uid() caching ────────────────
DROP POLICY IF EXISTS "billing_events_select" ON billing_events;
CREATE POLICY "billing_events_select" ON billing_events FOR SELECT
  USING (
    is_superadmin()
    OR current_user_org_role(organization_id) IN ('owner', 'admin')
  );

-- ── creative_assets: remove redundant FOR ALL service_role policy ─────────────
-- (service role bypasses RLS natively — policy was causing multiple_permissive_policies WARN)
DROP POLICY IF EXISTS "service_role_full_access_creative_assets" ON creative_assets;

DROP POLICY IF EXISTS "workspace_members_select_creative_assets" ON creative_assets;
CREATE POLICY "workspace_members_select_creative_assets"
  ON creative_assets FOR SELECT
  USING (workspace_id IN (
    SELECT workspace_id FROM workspace_members WHERE user_id = (SELECT auth.uid())
  ));

DROP POLICY IF EXISTS "workspace_members_insert_creative_assets" ON creative_assets;
CREATE POLICY "workspace_members_insert_creative_assets"
  ON creative_assets FOR INSERT
  WITH CHECK (workspace_id IN (
    SELECT workspace_id FROM workspace_members WHERE user_id = (SELECT auth.uid())
  ));

-- Simplified DELETE: was a 3-level correlated subquery; now a 2-table JOIN
DROP POLICY IF EXISTS "workspace_owners_delete_creative_assets" ON creative_assets;
CREATE POLICY "workspace_owners_delete_creative_assets"
  ON creative_assets FOR DELETE
  USING (EXISTS (
    SELECT 1
    FROM workspaces w
    JOIN organization_members om
      ON om.organization_id = w.organization_id
     AND om.user_id = (SELECT auth.uid())
     AND om.role IN ('owner', 'admin')
    WHERE w.id = creative_assets.workspace_id
  ));

-- ── campaign_benchmarks: split FOR ALL — restrict UPDATE/DELETE to owner/admin ─
-- Members could previously modify benchmark thresholds to suppress AI diagnostics.
DROP POLICY IF EXISTS campaign_benchmarks_select ON campaign_benchmarks;
CREATE POLICY campaign_benchmarks_select ON campaign_benchmarks FOR SELECT
  USING (
    workspace_id IS NULL
    OR workspace_id IN (
      SELECT workspace_id FROM workspace_members WHERE user_id = (SELECT auth.uid())
    )
  );

DROP POLICY IF EXISTS campaign_benchmarks_write ON campaign_benchmarks;
DROP POLICY IF EXISTS campaign_benchmarks_insert ON campaign_benchmarks;
DROP POLICY IF EXISTS campaign_benchmarks_update ON campaign_benchmarks;
DROP POLICY IF EXISTS campaign_benchmarks_delete ON campaign_benchmarks;

CREATE POLICY campaign_benchmarks_insert ON campaign_benchmarks FOR INSERT
  WITH CHECK (workspace_id IN (
    SELECT workspace_id FROM workspace_members
    WHERE user_id = (SELECT auth.uid()) AND role IN ('owner', 'admin')
  ));

CREATE POLICY campaign_benchmarks_update ON campaign_benchmarks FOR UPDATE
  USING (workspace_id IN (
    SELECT workspace_id FROM workspace_members
    WHERE user_id = (SELECT auth.uid()) AND role IN ('owner', 'admin')
  ));

CREATE POLICY campaign_benchmarks_delete ON campaign_benchmarks FOR DELETE
  USING (workspace_id IN (
    SELECT workspace_id FROM workspace_members
    WHERE user_id = (SELECT auth.uid()) AND role IN ('owner', 'admin')
  ));

-- ── ai_diagnostics: split FOR ALL — members can UPDATE status, not DELETE ─────
-- Diagnostic records are the AI audit trail; hard-delete must be blocked for users.
DROP POLICY IF EXISTS ai_diagnostics_select ON ai_diagnostics;
CREATE POLICY ai_diagnostics_select ON ai_diagnostics FOR SELECT
  USING (workspace_id IN (
    SELECT workspace_id FROM workspace_members WHERE user_id = (SELECT auth.uid())
  ));

DROP POLICY IF EXISTS ai_diagnostics_write ON ai_diagnostics;
DROP POLICY IF EXISTS ai_diagnostics_update ON ai_diagnostics;

CREATE POLICY ai_diagnostics_update ON ai_diagnostics FOR UPDATE
  USING (workspace_id IN (
    SELECT workspace_id FROM workspace_members
    WHERE user_id = (SELECT auth.uid()) AND role IN ('owner', 'admin', 'member')
  ))
  WITH CHECK (workspace_id IN (
    SELECT workspace_id FROM workspace_members
    WHERE user_id = (SELECT auth.uid()) AND role IN ('owner', 'admin', 'member')
  ));

-- ─────────────────────────────────────────────────────────────────────────────
-- 9. ADMIN SELF-ESCALATION PREVENTION
--    An admin must not be able to UPDATE their own row to role='owner'.
-- ─────────────────────────────────────────────────────────────────────────────

CREATE OR REPLACE FUNCTION prevent_org_member_self_escalation()
RETURNS TRIGGER LANGUAGE plpgsql SECURITY DEFINER
SET search_path = public, pg_temp AS $$
BEGIN
  IF NEW.user_id = (SELECT auth.uid())
     AND OLD.role = 'admin'
     AND NEW.role = 'owner'
     AND NOT is_superadmin()
  THEN
    RAISE EXCEPTION 'admins cannot self-promote to owner';
  END IF;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS org_members_no_self_escalation ON organization_members;
CREATE TRIGGER org_members_no_self_escalation
  BEFORE UPDATE ON organization_members
  FOR EACH ROW EXECUTE FUNCTION prevent_org_member_self_escalation();

-- ─────────────────────────────────────────────────────────────────────────────
-- 10. EXPLICIT DENY POLICIES ON APPEND-ONLY / IMMUTABLE TABLES
--     Documents intent and survives future policy additions.
-- ─────────────────────────────────────────────────────────────────────────────

-- billing_events: append-only Stripe audit log — deletion prohibited
DROP POLICY IF EXISTS "billing_events_no_delete" ON billing_events;
CREATE POLICY "billing_events_no_delete" ON billing_events FOR DELETE
  USING (false);

COMMENT ON TABLE billing_events IS
  'Append-only Stripe webhook audit log. Deletion intentionally prohibited (see policy billing_events_no_delete).';

-- creative_versions: immutable version history — no UPDATE or DELETE by design
DROP POLICY IF EXISTS creative_versions_update ON creative_versions;
CREATE POLICY creative_versions_update ON creative_versions FOR UPDATE
  USING (false);

DROP POLICY IF EXISTS creative_versions_delete ON creative_versions;
CREATE POLICY creative_versions_delete ON creative_versions FOR DELETE
  USING (false);

COMMENT ON TABLE creative_versions IS
  'Append-only creative version history. UPDATE and DELETE intentionally blocked by RLS.';

-- ─────────────────────────────────────────────────────────────────────────────
-- 11. ADD updated_at TO creative_assets
-- ─────────────────────────────────────────────────────────────────────────────

ALTER TABLE creative_assets
  ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW();

DROP TRIGGER IF EXISTS creative_assets_updated_at ON creative_assets;
CREATE TRIGGER creative_assets_updated_at
  BEFORE UPDATE ON creative_assets
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();
