import type { Creative, CopyVariation } from "@/types/database";

export const MOCK_CREATIVES: Creative[] = [
  {
    id: "cre_001",
    workspace_id: "ws_demo",
    campaign_id: "cmp_001",
    type: "copy",
    status: "approved",
    name: "Black Friday — Urgência",
    headline: "Black Friday: 50% OFF por tempo limitado!",
    description:
      "Não perca nossa maior promoção do ano. Milhares de produtos com desconto real. Aproveite agora antes que esgote!",
    cta: "Comprar agora",
    asset_url: null,
    thumbnail_url: null,
    format: null,
    prompt:
      "Crie um copy para Black Friday de e-commerce com foco em urgência e desconto",
    model_used: "gpt-4o",
    score: 87,
    score_breakdown: {
      clarity: 18,
      urgency: 20,
      cta_strength: 18,
      compliance: 16,
      relevance: 15,
    },
    policy_items: [
      { rule: "Sem afirmações enganosas", passed: true, detail: null },
      { rule: "CTA claro e direto", passed: true, detail: null },
      { rule: "Sem linguagem proibida Meta", passed: true, detail: null },
      { rule: "Desconto com termo de validade", passed: false, detail: 'Adicione prazo explícito, ex: "válido até 30/11"' },
    ],
    policy_passed: false,
    version: 1,
    parent_id: null,
    created_at: "2025-11-10T10:00:00Z",
    updated_at: "2025-11-10T10:00:00Z",
  },
  {
    id: "cre_003",
    workspace_id: "ws_demo",
    campaign_id: "cmp_002",
    type: "copy",
    status: "in_review",
    name: "Google Search — Marca Principal",
    headline: "AdFlow: Gestão de Campanhas com IA",
    description:
      "Automatize suas campanhas Meta e Google com inteligência artificial. Criativos gerados em segundos, resultados em dias.",
    cta: "Saiba mais",
    asset_url: null,
    thumbnail_url: null,
    format: null,
    prompt: "Copy para Google Search sobre plataforma de gestão de campanhas com IA",
    model_used: "gpt-4o",
    score: 91,
    score_breakdown: {
      clarity: 20,
      urgency: 16,
      cta_strength: 19,
      compliance: 19,
      relevance: 17,
    },
    policy_items: [
      { rule: "Título dentro de 30 caracteres (Google)", passed: false, detail: "Título com 38 chars — reduza para ≤30" },
      { rule: "Descrição dentro de 90 caracteres (Google)", passed: true, detail: null },
      { rule: "Sem uso indevido de marca registrada", passed: true, detail: null },
      { rule: "URL de destino funcional", passed: true, detail: null },
    ],
    policy_passed: false,
    version: 2,
    parent_id: "cre_003_v1",
    created_at: "2025-11-12T09:00:00Z",
    updated_at: "2025-11-13T11:30:00Z",
  },
  {
    id: "cre_006",
    workspace_id: "ws_demo",
    campaign_id: "cmp_002",
    type: "copy",
    status: "approved",
    name: "Google Leads — Variação B",
    headline: "Gerencie Campanhas com IA Real",
    description:
      "Plataforma AdTech completa para agências. Meta + Google + Pixel server-side + Analytics em um painel.",
    cta: "Teste grátis",
    asset_url: null,
    thumbnail_url: null,
    format: null,
    prompt: "Copy alternativo mais direto para geração de leads B2B agências digitais",
    model_used: "gpt-4o",
    score: 83,
    score_breakdown: {
      clarity: 18,
      urgency: 14,
      cta_strength: 20,
      compliance: 18,
      relevance: 13,
    },
    policy_items: [
      { rule: "Título dentro de 30 caracteres (Google)", passed: true, detail: null },
      { rule: "Descrição dentro de 90 caracteres (Google)", passed: false, detail: "Descrição com 95 chars — reduza 5 caracteres" },
      { rule: "Sem uso indevido de marca registrada", passed: true, detail: null },
      { rule: "URL de destino funcional", passed: true, detail: null },
    ],
    policy_passed: false,
    version: 1,
    parent_id: null,
    created_at: "2025-11-15T08:00:00Z",
    updated_at: "2025-11-15T08:00:00Z",
  },
  {
    id: "cre_007",
    workspace_id: "ws_demo",
    campaign_id: "cmp_001",
    type: "copy",
    status: "approved",
    name: "Black Friday — Benefício Direto",
    headline: "50% de desconto. Só hoje na Black Friday.",
    description:
      "Essa é a sua chance de economizar de verdade. Selecione seus produtos favoritos e finalize antes da meia-noite.",
    cta: "Aproveitar agora",
    asset_url: null,
    thumbnail_url: null,
    format: null,
    prompt: "Crie um copy para Black Friday de e-commerce com foco em urgência e desconto",
    model_used: "gpt-4o",
    score: 79,
    score_breakdown: {
      clarity: 17,
      urgency: 17,
      cta_strength: 16,
      compliance: 15,
      relevance: 14,
    },
    policy_items: [
      { rule: "Sem afirmações enganosas", passed: true, detail: null },
      { rule: "CTA claro e direto", passed: true, detail: null },
      { rule: "Sem linguagem proibida Meta", passed: true, detail: null },
      { rule: "Desconto com termo de validade", passed: true, detail: null },
    ],
    policy_passed: true,
    version: 1,
    parent_id: null,
    created_at: "2025-11-10T11:00:00Z",
    updated_at: "2025-11-10T11:00:00Z",
  },
  {
    id: "cre_008",
    workspace_id: "ws_demo",
    campaign_id: "cmp_003",
    type: "copy",
    status: "draft",
    name: "Retargeting — Carrinho Abandonado",
    headline: "Seu carrinho está esperando por você",
    description:
      "Você deixou itens incríveis para trás. Complete sua compra agora e garanta o frete grátis acima de R$199.",
    cta: "Finalizar compra",
    asset_url: null,
    thumbnail_url: null,
    format: null,
    prompt: "Copy retargeting carrinho abandonado, tom amigável e sem pressão excessiva",
    model_used: "gpt-4o",
    score: null,
    score_breakdown: null,
    policy_items: null,
    policy_passed: null,
    version: 1,
    parent_id: null,
    created_at: "2025-11-16T14:00:00Z",
    updated_at: "2025-11-16T14:00:00Z",
  },
];

// Mock copy variations returned by the AI generator
export const MOCK_COPY_VARIATIONS: CopyVariation[] = [
  {
    headline: "Black Friday: 50% OFF por tempo limitado!",
    description:
      "Não perca nossa maior promoção do ano. Milhares de produtos com desconto real. Aproveite agora antes que esgote!",
    cta: "Comprar agora",
  },
  {
    headline: "Últimas horas — desconto de até 50%",
    description:
      "A Black Friday chegou e os preços despencaram. Garanta os seus antes que o estoque acabe. Frete grátis acima de R$199.",
    cta: "Ver ofertas",
  },
  {
    headline: "50% de desconto. Só hoje na Black Friday.",
    description:
      "Essa é a sua chance de economizar de verdade. Selecione seus produtos favoritos e finalize antes da meia-noite.",
    cta: "Aproveitar agora",
  },
  {
    headline: "Black Friday real: metade do preço em tudo",
    description:
      "Sem pegadinha. Todos os produtos com 50% OFF durante 24 horas. Estoque limitado — corra para garantir o seu.",
    cta: "Garantir desconto",
  },
];
